name: "DevOps: Load Clinical Approved Changed Content"

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run in'
        type: environment
        required: true
      vaccine_name:
        description: 'Vaccine to update'
        type: choice
        options:
          - rsv
        required: true

env:
  AWS_REGION: eu-west-2
  AWS_CONTENT_CACHE_HYDRATOR_LAMBDA: gh-vita-${{ secrets.AWS_ACCOUNT_ID }}-content-cache-hydrator

jobs:
  hydrate:
    name: "Load new (${{inputs.vaccine_name}}) content in (${{ inputs.environment }})"
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    timeout-minutes: 5
    permissions:
      id-token: write
      contents: read
    steps:
      - name: "Check ref:${{ github.ref }} is a tag"
        run: |
          if ${{ !startsWith(github.ref, 'refs/tags/') }}; then
            echo "‚ùå Only tagged deployments allowed."
            exit 1
          fi
      - name: "Configure AWS credentials"
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-session-name: GitHubActionsSession
          role-to-assume: ${{ secrets.IAM_ROLE }}
          aws-region: ${{ env.AWS_REGION }}
      - name: "Run content-cache-hydrator for (${{ inputs.vaccine_name }}) vaccine in (${{ inputs.environment }})"
        run: |
          aws lambda invoke --function-name ${AWS_CONTENT_CACHE_HYDRATOR_LAMBDA} --cli-binary-format 'raw-in-base64-out' --payload '{"forceUpdate": true, "vaccineToUpdate": "${{ inputs.vaccine_name}}"}' response.json || {
            echo "Invocation of Content Cache Hydrator failed"
            cat response.json
            exit 1
          }
          if grep -q "errorMessage" response.json; then
            echo "Error during Content Cache Hydrator run"
            cat response.json
            exit 1
          fi
