name: "DevOps: Hydrate Content Cache"

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run hydrator in'
        type: environment
        required: true

env:
  AWS_REGION: eu-west-2
  AWS_CONTENT_CACHE_HYDRATOR_LAMBDA: gh-vita-${{ secrets.AWS_ACCOUNT_ID }}-content-cache-hydrator

jobs:
  hydrate:
    name: "Hydrate content-cache in (${{inputs.environment}})"
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    timeout-minutes: 5
    permissions:
      id-token: write
      contents: read
    steps:
      - name: "Check ref:${{github.ref}} is a tag"
        run: |
          if ${{ !startsWith(github.ref, 'refs/tags/') }}; then
            echo "‚ùå Only tagged deployments allowed."
            exit 1
          fi
      - name: "Configure AWS credentials"
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-session-name: GitHubActionsSession
          role-to-assume: ${{ secrets.IAM_ROLE }}
          aws-region: ${{ env.AWS_REGION }}
      - name: "Run content-cache-hydrator"
        run: |
          aws lambda invoke --function-name ${AWS_CONTENT_CACHE_HYDRATOR_LAMBDA} response.json || {
            echo "Invocation of Content Cache Hydrator failed"
            cat response.json
            exit 1
          }
          if grep -q "errorMessage" response.json; then
            echo "Error during Content Cache Hydrator run"
            cat response.json
            exit 1
          fi
