name: "DevOps: Load Clinical Approved Changed Content"

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run in'
        type: environment
        required: true
      vaccine_name:
        description: 'Vaccine to update'
        type: choice
        options:
          - rsv
          - rsv-pregnancy
          - td-ipv-vaccine-3-in-1-teenage-booster
          - 6-in-1-vaccine
          - rotavirus-vaccine
          - hpv-vaccine
          - menb-vaccine-for-children
          - mmr-vaccine
          - pneumococcal-vaccine
          - shingles-vaccine
          - menacwy-vaccine
          - 4-in-1-preschool-booster-vaccine
          - whooping-cough-vaccination
          - hib-menc-vaccine
          - flu-vaccine-in-pregnancy
          - covid-19-vaccine
          - flu-vaccine
          - flu-vaccine-for-children
          - flu-vaccine-for-school-aged-children
        required: true

env:
  AWS_REGION: eu-west-2
  AWS_CONTENT_CACHE_HYDRATOR_LAMBDA: gh-vita-${{ secrets.AWS_ACCOUNT_ID }}-content-cache-hydrator

jobs:
  hydrate:
    name: "Reload (${{inputs.vaccine_name}}) content"
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    timeout-minutes: 5
    permissions:
      id-token: write
      contents: read
    steps:
      - name: "Configure AWS credentials"
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-session-name: GitHubActionsSession
          role-to-assume: ${{ secrets.IAM_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: "Run content-cache-hydrator for (${{ inputs.vaccine_name }}) vaccine in (${{ inputs.environment }})"
        run: |
          aws lambda invoke --function-name ${AWS_CONTENT_CACHE_HYDRATOR_LAMBDA} --cli-binary-format 'raw-in-base64-out' --payload '{"forceUpdate": true, "vaccineToUpdate": "${{ inputs.vaccine_name}}"}' response.json || {
            echo "Invocation of Content Cache Hydrator failed"
            cat response.json
            exit 1
          }
          if grep -q "errorMessage" response.json; then
            echo "Error during Content Cache Hydrator run"
            cat response.json
            exit 1
          fi
